language: r
sudo: false
warnings_are_errors: false
cache: packages


bioc_required: true
bioc_packages:
  - BiocCheck



after_script:
  - ls -lah
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")"







addons:
  apt:
     sources:
     - ubuntu-toolchain-r-test
     packages:
     - gcc-4.8
     - g++-4.8
     - libcurl4-openssl-dev
     - libgsl-dev
  
notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual --no-resave-data"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"
    - CXX="g++-4.8"
    - CC="gcc-4.8"

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
